In [1]:
from sympy import *
import numpy as np
from IPython.display import display
import sys
# sys.path.insert(1, '../lab01')


In [2]:
x1 = Symbol('x1')
x2 = Symbol('x2')
# f = simplify(x1 ** 2 + x2 ** 2 + 6 * x1 - 10*x2)


# f1 = simplify(x1**2 + x2**2 + 6 * x1 - 10 * x2 + x1**4)
f1 = simplify(100 * (x2 - x1)**2 + (1 - x1)**2)
f2 = simplify(100 * (x2 - x1 ** 2) ** 2 + (1 - x1) ** 2)
f3 = -simplify(2 * exp(-(x1 - 1) ** 2 / 4 - (x2 - 1) ** 2 / 1) + 3 * exp(-(x1 - 2) ** 2 / 9 - (x2 - 3) ** 2 / 4))
freeSyms = f1.free_symbols
eps = 1e-9
print('eps =', eps)
funcs = [f3]
funcs

eps = 1e-09


[-3*exp(-(x1 - 2)**2/9 - (x2 - 3)**2/4) - 2*exp(-(x1 - 1)**2/4 - (x2 - 1)**2)]

In [3]:
def hessian(func):
    fs = func.free_symbols
    return Matrix(derive_by_array(derive_by_array(func, fs), fs))

def gradient(func):
    return Matrix(derive_by_array(func, func.free_symbols))

def substitute(u, x):
    return Matrix(u.applyfunc(lambda k: k.evalf(subs=dict(zip(freeSyms, x)))))

def positive_definitive(m):
    eigenvalues = np.linalg.eigvals(m)
    display("before", eigenvalues)
    if all(eigenvalues > 0):
        return m
    else:
        min_eig = min(eigenvalues)
        add = 2 * (-min_eig) * np.eye(m.shape[0])
        display("after", np.linalg.eigvals(m + add))
        return m + add

In [4]:
def newton(f, x_start, eps):
    result = OptimizeResult("dichotomy", w, 0, 0, 0, [])
    h = hessian(f)
    grad = gradient(f)
    prevY = float('inf')
    curX = x_start
    curY = f.evalf(subs=dict(zip(freeSyms, curX)))


    while abs(curY - prevY) > eps:
        prevY = curY


In [5]:
for f in funcs:
    display("-"*100)
    h = hessian(f)
    grad = gradient(f)
    display(h)
    display(grad[0])
    display(grad[1])

    prevY = float('inf')
    curX = Matrix([0, 1])

    h.applyfunc(lambda k: k.evalf(subs=dict(zip(freeSyms, curX))))

    curY = f.evalf(subs=dict(zip(freeSyms, curX)))
    display(('curY= ', curY))

    # while abs(curY - prevY) > eps:
    for i in range(10):
      prevY = curY
      hMin1 = substitute(h, curX)
      # display(("h", hMin1))
      hMin1 = positive_definitive(np.array(hMin1, dtype=float))
      hMin1 = Matrix(hMin1)
      # display("correctHesse", hMin1)
      # display("hInv", hMin1.inv())
      # print("grad =", substitute(grad, curX))
      newX = curX - hMin1.inv() * substitute(grad, curX)
      # print("newX =", newX)
      display(curX - newX)
      curX = newX
      curY = f.evalf(subs=dict(zip(freeSyms, curX)))
      display(('curY= ', curY))
      display(('curX= ', curX))

    display(curX)



'----------------------------------------------------------------------------------------------------'

Matrix([
[(3/2 - x2/2)*(3*x2/2 - 9/2)*exp(-(x1 - 2)**2/9 - (x2 - 3)**2/4) + (2 - 2*x2)*(4*x2 - 4)*exp(-(x1 - 1)**2/4 - (x2 - 1)**2) + 3*exp(-(x1 - 2)**2/9 - (x2 - 3)**2/4)/2 + 4*exp(-(x1 - 1)**2/4 - (x2 - 1)**2),                                                                                   (3/2 - x2/2)*(2*x1/3 - 4/3)*exp(-(x1 - 2)**2/9 - (x2 - 3)**2/4) + (2 - 2*x2)*(x1 - 1)*exp(-(x1 - 1)**2/4 - (x2 - 1)**2)],
[                                                                            (4/9 - 2*x1/9)*(3*x2/2 - 9/2)*exp(-(x1 - 2)**2/9 - (x2 - 3)**2/4) + (1/2 - x1/2)*(4*x2 - 4)*exp(-(x1 - 1)**2/4 - (x2 - 1)**2), (4/9 - 2*x1/9)*(2*x1/3 - 4/3)*exp(-(x1 - 2)**2/9 - (x2 - 3)**2/4) + (1/2 - x1/2)*(x1 - 1)*exp(-(x1 - 1)**2/4 - (x2 - 1)**2) + 2*exp(-(x1 - 2)**2/9 - (x2 - 3)**2/4)/3 + exp(-(x1 - 1)**2/4 - (x2 - 1)**2)]])

-3*(3/2 - x2/2)*exp(-(x1 - 2)**2/9 - (x2 - 3)**2/4) - 2*(2 - 2*x2)*exp(-(x1 - 1)**2/4 - (x2 - 1)**2)

-3*(4/9 - 2*x1/9)*exp(-(x1 - 2)**2/9 - (x2 - 3)**2/4) - 2*(1/2 - x1/2)*exp(-(x1 - 1)**2/4 - (x2 - 1)**2)

('curY= ', -1.01870499264199)

'before'

array([-1.97039977,  0.42051002])

'after'

array([1.97039977, 4.36130956])

Matrix([
[ -0.962077244647985],
[-0.0352524727910908]])

('curY= ', -2.95433509091525)

('curX= ',
 Matrix([
 [0.962077244647985],
 [ 1.03525247279109]]))

'before'

array([3.48435294, 1.14804952])

Matrix([
[-0.337541354946254],
[-0.205650773636935]])

('curY= ', -3.16777676185211)

('curX= ',
 Matrix([
 [1.29961859959424],
 [1.24090324642803]]))

'before'

array([2.71973049, 1.07225107])

Matrix([
[-0.0333074898973387],
[-0.0212452522915973]])

('curY= ', -3.16931457001761)

('curX= ',
 Matrix([
 [1.33292608949158],
 [1.26214849871962]]))

'before'

array([2.54879526, 1.04076418])

Matrix([
[ -0.00146691800407961],
[-0.000884770879667762]])

('curY= ', -3.16931721621443)

('curX= ',
 Matrix([
 [1.33439300749566],
 [1.26303326959929]]))

'before'

array([2.54111676, 1.03924527])

Matrix([
[-2.95502043479168e-6],
[-1.75529061796631e-6]])

('curY= ', -3.16931721622508)

('curX= ',
 Matrix([
 [1.33439596251609],
 [1.26303502488991]]))

'before'

array([2.54110129, 1.03924221])

Matrix([
[-1.19857457292483e-11],
[-7.09343694893505e-12]])

('curY= ', -3.16931721622508)

('curX= ',
 Matrix([
 [1.33439596252808],
 [  1.263035024897]]))

'before'

array([2.54110129, 1.03924221])

Matrix([
[0],
[0]])

('curY= ', -3.16931721622508)

('curX= ',
 Matrix([
 [1.33439596252808],
 [  1.263035024897]]))

'before'

array([2.54110129, 1.03924221])

Matrix([
[0],
[0]])

('curY= ', -3.16931721622508)

('curX= ',
 Matrix([
 [1.33439596252808],
 [  1.263035024897]]))

'before'

array([2.54110129, 1.03924221])

Matrix([
[0],
[0]])

('curY= ', -3.16931721622508)

('curX= ',
 Matrix([
 [1.33439596252808],
 [  1.263035024897]]))

'before'

array([2.54110129, 1.03924221])

Matrix([
[0],
[0]])

('curY= ', -3.16931721622508)

('curX= ',
 Matrix([
 [1.33439596252808],
 [  1.263035024897]]))

Matrix([
[1.33439596252808],
[  1.263035024897]])